/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.game2d;

import com.mycompany.game2d.personaggi.Eroe;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Esposito.Lorenzo
 */
public class FrameInventario extends javax.swing.JFrame {
    private Eroe er;
    private javax.swing.JLabel SlotInventario[];
    /**
     * Creates new form FrameInventario
     */
    public FrameInventario(Eroe er) {
        initComponents();
         this.SlotInventario = new javax.swing.JLabel[]{Slot1,Slot2,Slot3,Slot4,Slot5,Slot6,Slot7,Slot8,Slot9};
        super.getContentPane().setBackground(Color.BLACK);
        super.setSize(400,350);
        this.er = er;
        ImageIcon icona = sclareImagni(er.getMano().getTexture());
        SlotInventario[0].setIcon(icona);
        for(int i=1;i<=er.getInvetario().size()&&i<7;i++){
             icona = sclareImagni(er.getInvetario().get(i-1).getTexture());
            SlotInventario[i].setIcon(icona);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slot1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Slot2 = new javax.swing.JLabel();
        Slot3 = new javax.swing.JLabel();
        Slot4 = new javax.swing.JLabel();
        Slot5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Slot6 = new javax.swing.JLabel();
        Slot8 = new javax.swing.JLabel();
        Slot9 = new javax.swing.JLabel();
        Slot7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Slot1.setBackground(new java.awt.Color(102, 51, 0));
        Slot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot1.setAutoscrolls(true);
        Slot1.setDoubleBuffered(true);
        Slot1.setFocusCycleRoot(true);
        Slot1.setFocusTraversalPolicyProvider(true);
        Slot1.setOpaque(true);
        Slot1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Slot1FocusGained(evt);
            }
        });
        Slot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot1MouseClicked(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jButton1.setText("UTILLIZA");

        jButton2.setText("EQUIPAGGIA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(232, 232, 232));
        jLabel3.setText("jLabel3");

        jLabel4.setText("Quantita");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("jLabel5");

        Slot2.setBackground(new java.awt.Color(102, 51, 0));
        Slot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot2.setAutoscrolls(true);
        Slot2.setDoubleBuffered(true);
        Slot2.setFocusCycleRoot(true);
        Slot2.setFocusTraversalPolicyProvider(true);
        Slot2.setFocusable(false);
        Slot2.setOpaque(true);

        Slot3.setBackground(new java.awt.Color(102, 51, 0));
        Slot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot3.setAutoscrolls(true);
        Slot3.setDoubleBuffered(true);
        Slot3.setFocusCycleRoot(true);
        Slot3.setFocusTraversalPolicyProvider(true);
        Slot3.setFocusable(false);
        Slot3.setOpaque(true);

        Slot4.setBackground(new java.awt.Color(102, 51, 0));
        Slot4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot4.setAutoscrolls(true);
        Slot4.setDoubleBuffered(true);
        Slot4.setFocusCycleRoot(true);
        Slot4.setFocusTraversalPolicyProvider(true);
        Slot4.setFocusable(false);
        Slot4.setOpaque(true);

        Slot5.setBackground(new java.awt.Color(102, 51, 0));
        Slot5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot5.setAutoscrolls(true);
        Slot5.setDoubleBuffered(true);
        Slot5.setFocusCycleRoot(true);
        Slot5.setFocusTraversalPolicyProvider(true);
        Slot5.setFocusable(false);
        Slot5.setOpaque(true);

        jLabel10.setText("Pag:");

        jLabel11.setText("jLabel11");

        Slot6.setBackground(new java.awt.Color(102, 51, 0));
        Slot6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot6.setAutoscrolls(true);
        Slot6.setDoubleBuffered(true);
        Slot6.setFocusCycleRoot(true);
        Slot6.setFocusTraversalPolicyProvider(true);
        Slot6.setFocusable(false);
        Slot6.setOpaque(true);

        Slot8.setBackground(new java.awt.Color(102, 51, 0));
        Slot8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot8.setAutoscrolls(true);
        Slot8.setDoubleBuffered(true);
        Slot8.setFocusCycleRoot(true);
        Slot8.setFocusTraversalPolicyProvider(true);
        Slot8.setFocusable(false);
        Slot8.setOpaque(true);

        Slot9.setBackground(new java.awt.Color(102, 51, 0));
        Slot9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot9.setAutoscrolls(true);
        Slot9.setDoubleBuffered(true);
        Slot9.setFocusCycleRoot(true);
        Slot9.setFocusTraversalPolicyProvider(true);
        Slot9.setFocusable(false);
        Slot9.setOpaque(true);

        Slot7.setBackground(new java.awt.Color(102, 51, 0));
        Slot7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot7.setAutoscrolls(true);
        Slot7.setDoubleBuffered(true);
        Slot7.setFocusCycleRoot(true);
        Slot7.setFocusTraversalPolicyProvider(true);
        Slot7.setFocusable(false);
        Slot7.setOpaque(true);

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(67, 67, 67))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Slot1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Slot1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Slot1FocusGained
        // TODO add your handling code here
    }//GEN-LAST:event_Slot1FocusGained

    private void Slot1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot1MouseClicked
        // TODO add your handling code here:
        Icon tt;
        tt= Slot1.getIcon();
        jLabel2.setIcon(tt);
    }//GEN-LAST:event_Slot1MouseClicked
    private ImageIcon sclareImagni(String path){
        ImageIcon icona = new ImageIcon(path); // load the image to a imageIcon
        Image imagineog = icona.getImage(); // transform it 
        Image imagineinven = imagineog.getScaledInstance(32, 32,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        return icona = new ImageIcon(imagineinven);  // transform it back
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Slot1;
    private javax.swing.JLabel Slot2;
    private javax.swing.JLabel Slot3;
    private javax.swing.JLabel Slot4;
    private javax.swing.JLabel Slot5;
    private javax.swing.JLabel Slot6;
    private javax.swing.JLabel Slot7;
    private javax.swing.JLabel Slot8;
    private javax.swing.JLabel Slot9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
