/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.game2d;

import com.mycompany.game2d.oggetto.Oggetto;
import com.mycompany.game2d.personaggi.Eroe;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Esposito.Lorenzo
 */
public class FrameInventario extends javax.swing.JFrame {
    private Eroe er;
    private int FocusIndex;
    private javax.swing.JLabel SlotInventario[];
    ImageIcon icona;
    private FrameMappa frameMappa;
    /**
     * Creates new form FrameInventario
     */
    public FrameInventario(Eroe er,FrameMappa frameMappa) {
        initComponents();
        this.frameMappa = frameMappa;
         SlotInventario = new javax.swing.JLabel[]{Slot1,Slot2,Slot3,Slot4,Slot5,Slot6,Slot7,Slot8,Slot9};
        super.getContentPane().setBackground(Color.BLACK);
        super.setSize(400,350);
        this.er = er;
        updetIvent();
    }


    private void updetIvent(){
        icona = sclareImagni(er.getMano().getTexture());
        SlotInventario[0].setIcon(icona);
        for(int i=1;i<=er.getInvetario().size()&&i<7;i++){
            icona = sclareImagni(er.getInvetario().get(i-1).getTexture());
            SlotInventario[i].setIcon(icona);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slot1 = new javax.swing.JLabel();
        LabelDescrizone = new javax.swing.JLabel();
        ButtonUtilizza = new javax.swing.JButton();
        ButtonEquipaggia = new javax.swing.JButton();
        LabelNome = new javax.swing.JLabel();
        LabelQunatita = new javax.swing.JLabel();
        LabelQunaitaVal = new javax.swing.JLabel();
        Slot2 = new javax.swing.JLabel();
        Slot3 = new javax.swing.JLabel();
        Slot4 = new javax.swing.JLabel();
        Slot5 = new javax.swing.JLabel();
        LabelPag = new javax.swing.JLabel();
        LabelPagVal = new javax.swing.JLabel();
        Slot6 = new javax.swing.JLabel();
        Slot8 = new javax.swing.JLabel();
        Slot9 = new javax.swing.JLabel();
        Slot7 = new javax.swing.JLabel();
        ButtonIndietro = new javax.swing.JButton();
        ButtonAvanti = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Slot1.setBackground(new java.awt.Color(71, 45, 60));
        Slot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot1.setAutoscrolls(true);
        Slot1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot1.setDoubleBuffered(true);
        Slot1.setFocusCycleRoot(true);
        Slot1.setFocusTraversalPolicyProvider(true);
        Slot1.setOpaque(true);
        Slot1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Slot1FocusGained(evt);
            }
        });
        Slot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot1MouseClicked(evt);
            }
        });

        LabelDescrizone.setForeground(new java.awt.Color(232, 232, 232));
        LabelDescrizone.setText(" ");

        ButtonUtilizza.setBackground(new java.awt.Color(84, 84, 84));
        ButtonUtilizza.setForeground(new java.awt.Color(232, 232, 232));
        ButtonUtilizza.setText("UTILLIZA");
        ButtonUtilizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUtilizzaActionPerformed(evt);
            }
        });

        ButtonEquipaggia.setBackground(new java.awt.Color(84, 84, 84));
        ButtonEquipaggia.setForeground(new java.awt.Color(232, 232, 232));
        ButtonEquipaggia.setText("EQUIPAGGIA");
        ButtonEquipaggia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEquipaggiaActionPerformed(evt);
            }
        });

        LabelNome.setForeground(new java.awt.Color(232, 232, 232));
        LabelNome.setText(" ");

        LabelQunatita.setForeground(new java.awt.Color(232, 232, 232));
        LabelQunatita.setText("Quantita");

        LabelQunaitaVal.setForeground(new java.awt.Color(232, 232, 232));
        LabelQunaitaVal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LabelQunaitaVal.setText(" ");

        Slot2.setBackground(new java.awt.Color(71, 45, 60));
        Slot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot2.setAutoscrolls(true);
        Slot2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot2.setDoubleBuffered(true);
        Slot2.setFocusCycleRoot(true);
        Slot2.setFocusTraversalPolicyProvider(true);
        Slot2.setFocusable(false);
        Slot2.setOpaque(true);
        Slot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot2MouseClicked(evt);
            }
        });

        Slot3.setBackground(new java.awt.Color(71, 45, 60));
        Slot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot3.setAutoscrolls(true);
        Slot3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot3.setDoubleBuffered(true);
        Slot3.setFocusCycleRoot(true);
        Slot3.setFocusTraversalPolicyProvider(true);
        Slot3.setFocusable(false);
        Slot3.setOpaque(true);
        Slot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot3MouseClicked(evt);
            }
        });

        Slot4.setBackground(new java.awt.Color(71, 45, 60));
        Slot4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot4.setAutoscrolls(true);
        Slot4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot4.setDoubleBuffered(true);
        Slot4.setFocusCycleRoot(true);
        Slot4.setFocusTraversalPolicyProvider(true);
        Slot4.setFocusable(false);
        Slot4.setOpaque(true);
        Slot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot4MouseClicked(evt);
            }
        });

        Slot5.setBackground(new java.awt.Color(71, 45, 60));
        Slot5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot5.setAutoscrolls(true);
        Slot5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot5.setDoubleBuffered(true);
        Slot5.setFocusCycleRoot(true);
        Slot5.setFocusTraversalPolicyProvider(true);
        Slot5.setFocusable(false);
        Slot5.setOpaque(true);
        Slot5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot5MouseClicked(evt);
            }
        });

        LabelPag.setForeground(new java.awt.Color(232, 232, 232));
        LabelPag.setText("Pag:");

        LabelPagVal.setForeground(new java.awt.Color(232, 232, 232));
        LabelPagVal.setText("1");

        Slot6.setBackground(new java.awt.Color(71, 45, 60));
        Slot6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot6.setAutoscrolls(true);
        Slot6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot6.setDoubleBuffered(true);
        Slot6.setFocusCycleRoot(true);
        Slot6.setFocusTraversalPolicyProvider(true);
        Slot6.setFocusable(false);
        Slot6.setOpaque(true);
        Slot6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot6MouseClicked(evt);
            }
        });

        Slot8.setBackground(new java.awt.Color(71, 45, 60));
        Slot8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot8.setAutoscrolls(true);
        Slot8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot8.setDoubleBuffered(true);
        Slot8.setFocusCycleRoot(true);
        Slot8.setFocusTraversalPolicyProvider(true);
        Slot8.setFocusable(false);
        Slot8.setOpaque(true);
        Slot8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot8MouseClicked(evt);
            }
        });

        Slot9.setBackground(new java.awt.Color(71, 45, 60));
        Slot9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot9.setAutoscrolls(true);
        Slot9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot9.setDoubleBuffered(true);
        Slot9.setFocusCycleRoot(true);
        Slot9.setFocusTraversalPolicyProvider(true);
        Slot9.setFocusable(false);
        Slot9.setOpaque(true);
        Slot9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot9MouseClicked(evt);
            }
        });

        Slot7.setBackground(new java.awt.Color(71, 45, 60));
        Slot7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Slot7.setAutoscrolls(true);
        Slot7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        Slot7.setDoubleBuffered(true);
        Slot7.setFocusCycleRoot(true);
        Slot7.setFocusTraversalPolicyProvider(true);
        Slot7.setFocusable(false);
        Slot7.setOpaque(true);
        Slot7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Slot7MouseClicked(evt);
            }
        });

        ButtonIndietro.setBackground(new java.awt.Color(84, 84, 84));
        ButtonIndietro.setForeground(new java.awt.Color(232, 232, 232));
        ButtonIndietro.setText("<----");

        ButtonAvanti.setBackground(new java.awt.Color(84, 84, 84));
        ButtonAvanti.setForeground(new java.awt.Color(232, 232, 232));
        ButtonAvanti.setText("---->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ButtonEquipaggia, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(ButtonUtilizza, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelQunatita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelQunaitaVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(LabelDescrizone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonIndietro)
                        .addGap(220, 220, 220)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelPagVal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(ButtonAvanti))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slot9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonIndietro)
                    .addComponent(LabelPagVal)
                    .addComponent(LabelPag)
                    .addComponent(ButtonAvanti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(LabelQunatita)
                    .addComponent(LabelQunaitaVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonUtilizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEquipaggia))
                    .addComponent(LabelDescrizone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Slot1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEquipaggiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEquipaggiaActionPerformed
        // TODO add your handling code here:
        Oggetto og;
        og= er.getMano();
        er.setMano(er.getInvetario().get(FocusIndex));
        er.getInvetario().remove(FocusIndex);
        er.getInvetario().add(og);
        updetIvent();
    }//GEN-LAST:event_ButtonEquipaggiaActionPerformed

    private void Slot1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Slot1FocusGained
        // TODO add your handling code here
    }//GEN-LAST:event_Slot1FocusGained

    private void Slot1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot1MouseClicked
        // TODO add your handling code here:
        if(Slot1.getIcon()!=null){
            ImagFocus(er.getMano());
            FocusIndex=-1;
        }
    }//GEN-LAST:event_Slot1MouseClicked

    private void Slot2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot2MouseClicked
        // TODO add your handling code here:
         if(Slot2.getIcon()!=null){
            ImagFocus(er.getInvetario().get(0));
            FocusIndex=0;
        }
    }//GEN-LAST:event_Slot2MouseClicked

    private void Slot3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot3MouseClicked
        // TODO add your handling code here:
         if(Slot3.getIcon()!=null){
             ImagFocus(er.getInvetario().get(1));
             FocusIndex=1;
        }
    }//GEN-LAST:event_Slot3MouseClicked

    private void Slot4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot4MouseClicked
        // TODO add your handling code here:
         if(Slot4.getIcon()!=null){
             ImagFocus(er.getInvetario().get(2));
             FocusIndex=2;
        }
    }//GEN-LAST:event_Slot4MouseClicked

    private void Slot5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot5MouseClicked
        // TODO add your handling code here:
        if(Slot5.getIcon()!=null){
             ImagFocus(er.getInvetario().get(3));
             FocusIndex=3;
        }
    }//GEN-LAST:event_Slot5MouseClicked

    private void Slot6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot6MouseClicked
        // TODO add your handling code here:
        if(Slot6.getIcon()!=null){
             ImagFocus(er.getInvetario().get(4));
             FocusIndex=4;
        }
    }//GEN-LAST:event_Slot6MouseClicked

    private void Slot7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot7MouseClicked
        // TODO add your handling code here:
        if(Slot7.getIcon()!=null){
             ImagFocus(er.getInvetario().get(5));
             FocusIndex=5;
        }
    }//GEN-LAST:event_Slot7MouseClicked

    private void Slot8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot8MouseClicked
        // TODO add your handling code here:
        if(Slot7.getIcon()!=null){
             ImagFocus(er.getInvetario().get(6));
             FocusIndex=6;
        }
    }//GEN-LAST:event_Slot8MouseClicked

    private void Slot9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Slot9MouseClicked
        // TODO add your handling code here:
        if(Slot9.getIcon()!=null){
             ImagFocus(er.getInvetario().get(7));
             FocusIndex=7;
        }
    }//GEN-LAST:event_Slot9MouseClicked

    private void ButtonUtilizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUtilizzaActionPerformed
        // TODO add your handling code here:
        if(FocusIndex==-1&&er.getMano()!=null){
            er.getMano().Danno(er,er.getMano());
        }else if(er.getInvetario().get(FocusIndex)!=null){
            er.getInvetario().get(FocusIndex).Danno(er,er.getInvetario().get(FocusIndex));
            if(er.getInvetario().get(FocusIndex).getQuatita()==0){
                er.getInvetario().remove(FocusIndex);

            }
        }
        frameMappa.Updatebars();

    }//GEN-LAST:event_ButtonUtilizzaActionPerformed
    private ImageIcon sclareImagni(String path){
        ImageIcon icona = new ImageIcon(path); // load the image to a imageIcon
        Image imagineog = icona.getImage(); // transform it
        Image imagineinven = imagineog.getScaledInstance(32, 32,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        return icona = new ImageIcon(imagineinven);  // transform it back
    }
    private void ImagFocus(Oggetto og){
        LabelNome.setText(og.getNome());
        LabelQunaitaVal.setText(String.valueOf(og.getQuatita()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAvanti;
    private javax.swing.JButton ButtonEquipaggia;
    private javax.swing.JButton ButtonIndietro;
    private javax.swing.JButton ButtonUtilizza;
    private javax.swing.JLabel LabelDescrizone;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelPag;
    private javax.swing.JLabel LabelPagVal;
    private javax.swing.JLabel LabelQunaitaVal;
    private javax.swing.JLabel LabelQunatita;
    private javax.swing.JLabel Slot1;
    private javax.swing.JLabel Slot2;
    private javax.swing.JLabel Slot3;
    private javax.swing.JLabel Slot4;
    private javax.swing.JLabel Slot5;
    private javax.swing.JLabel Slot6;
    private javax.swing.JLabel Slot7;
    private javax.swing.JLabel Slot8;
    private javax.swing.JLabel Slot9;
    // End of variables declaration//GEN-END:variables
}
