package com.mycompany.game2d;

import javax.swing.*;
import java.awt.Color;
import java.lang.Thread;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Esposito.Lorenzo
 */
public class Game2dForm extends JFrame implements Runnable{
    private int Creation=20;
    private GameMap Gmap;
    private GamePanel Gpanel;
    protected Eroe er=null;
    private Thread gameThread;
    private final int gameTime = 120;
    /**
     * Creates new form Game2dForm
     */
    public Game2dForm() {
        initComponents();
        FrameCreazione.setSize(400, 500);
        FrameCreazione.getContentPane().setBackground(Color.BLACK);
        super.getContentPane().setBackground(Color.BLACK);
        super.setSize(400,300);
        FrameOpzione.setSize(300,200);
        FrameOpzione.getContentPane().setBackground(Color.BLACK);
        Gpanel = new GamePanel();
        Gmap = new GameMap(Gpanel);
        Gpanel.addKeyListener(new GameInput(Gpanel));
        Gpanel.requestFocus();
        gamestart();

    }
    private void gamestart(){
        gameThread = new Thread(this);
        gameThread.start();
    }
    @Override
    public void run() {
        double timeFreme = 1000000000.0/gameTime;
        long lastTime = System.nanoTime();
        long now = System.nanoTime();
        while (true){
            now = System.nanoTime();
            if(now - lastTime >= timeFreme){

                Gpanel.repaint();
                lastTime = now;

            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameCreazione = new javax.swing.JFrame();
        LabelNome = new javax.swing.JLabel();
        TextFieldNome = new javax.swing.JTextField();
        LabelVelocita = new javax.swing.JLabel();
        ButtonConfremaCrea = new javax.swing.JButton();
        ButtonMenVel = new javax.swing.JButton();
        LabelValVel = new javax.swing.JLabel();
        ButtonpiuVel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        FrameOpzione = new javax.swing.JFrame();
        LabelLingua = new javax.swing.JLabel();
        ComboLingue = new javax.swing.JComboBox<>();
        ButtonSelezionaLIngua = new javax.swing.JButton();
        LabelTitoloOpzione = new javax.swing.JLabel();
        ButtonNuovaPartita = new javax.swing.JButton();
        ButtonContinuaPartita = new javax.swing.JButton();
        ButtonOpzione = new javax.swing.JButton();
        LabelTitolo = new javax.swing.JLabel();

        FrameCreazione.setBackground(new java.awt.Color(0, 0, 0));

        LabelNome.setForeground(new java.awt.Color(232, 232, 232));
        LabelNome.setText("Nome:");

        TextFieldNome.setForeground(new java.awt.Color(232, 232, 232));
        TextFieldNome.setText("jTextField1");

        LabelVelocita.setForeground(new java.awt.Color(232, 232, 232));
        LabelVelocita.setText("Velocita");

        ButtonConfremaCrea.setBackground(new java.awt.Color(84, 84, 84));
        ButtonConfremaCrea.setForeground(new java.awt.Color(232, 232, 232));
        ButtonConfremaCrea.setText("Conferma");
        ButtonConfremaCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfremaCreaActionPerformed(evt);
            }
        });

        ButtonMenVel.setBackground(new java.awt.Color(84, 84, 84));
        ButtonMenVel.setForeground(new java.awt.Color(232, 232, 232));
        ButtonMenVel.setText("-");
        ButtonMenVel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenVelActionPerformed(evt);
            }
        });

        LabelValVel.setForeground(new java.awt.Color(232, 232, 232));
        LabelValVel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValVel.setText("0");

        ButtonpiuVel.setBackground(new java.awt.Color(84, 84, 84));
        ButtonpiuVel.setForeground(new java.awt.Color(232, 232, 232));
        ButtonpiuVel.setText("+");

        javax.swing.GroupLayout FrameCreazioneLayout = new javax.swing.GroupLayout(FrameCreazione.getContentPane());
        FrameCreazione.getContentPane().setLayout(FrameCreazioneLayout);
        FrameCreazioneLayout.setHorizontalGroup(
            FrameCreazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCreazioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameCreazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameCreazioneLayout.createSequentialGroup()
                        .addComponent(LabelVelocita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonMenVel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelValVel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonpiuVel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FrameCreazioneLayout.createSequentialGroup()
                        .addComponent(LabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameCreazioneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonConfremaCrea)
                .addContainerGap())
        );
        FrameCreazioneLayout.setVerticalGroup(
            FrameCreazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameCreazioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameCreazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameCreazioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelVelocita)
                    .addComponent(ButtonMenVel)
                    .addComponent(LabelValVel)
                    .addComponent(ButtonpiuVel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(ButtonConfremaCrea)
                .addContainerGap())
        );

        FrameOpzione.setBackground(new java.awt.Color(0, 0, 0));

        LabelLingua.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LabelLingua.setText("Lingue");

        ComboLingue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Italiano", "English" }));

        ButtonSelezionaLIngua.setText("Seleziona");

        LabelTitoloOpzione.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelTitoloOpzione.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitoloOpzione.setText("Opzioni Lingua");

        javax.swing.GroupLayout FrameOpzioneLayout = new javax.swing.GroupLayout(FrameOpzione.getContentPane());
        FrameOpzione.getContentPane().setLayout(FrameOpzioneLayout);
        FrameOpzioneLayout.setHorizontalGroup(
            FrameOpzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameOpzioneLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(FrameOpzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LabelTitoloOpzione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FrameOpzioneLayout.createSequentialGroup()
                        .addComponent(LabelLingua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboLingue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSelezionaLIngua)))
                .addGap(44, 44, 44))
        );
        FrameOpzioneLayout.setVerticalGroup(
            FrameOpzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameOpzioneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitoloOpzione, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(FrameOpzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLingua)
                    .addComponent(ComboLingue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSelezionaLIngua))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La Terrra dei Fiordalsi");
        setBackground(Color.BLACK);

        ButtonNuovaPartita.setBackground(new java.awt.Color(84, 84, 84));
        ButtonNuovaPartita.setForeground(new java.awt.Color(232, 232, 232));
        ButtonNuovaPartita.setText("Nuova Partita");
        ButtonNuovaPartita.setToolTipText("");
        ButtonNuovaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNuovaPartitaActionPerformed(evt);
            }
        });

        ButtonContinuaPartita.setBackground(new java.awt.Color(84, 84, 84));
        ButtonContinuaPartita.setForeground(new java.awt.Color(232, 232, 232));
        ButtonContinuaPartita.setText("Continua Partita");

        ButtonOpzione.setBackground(new java.awt.Color(84, 84, 84));
        ButtonOpzione.setForeground(new java.awt.Color(232, 232, 232));
        ButtonOpzione.setText("Opzione");
        ButtonOpzione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpzioneActionPerformed(evt);
            }
        });

        LabelTitolo.setBackground(new java.awt.Color(98, 44, 28));
        LabelTitolo.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        LabelTitolo.setForeground(new java.awt.Color(255, 255, 255));
        LabelTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTitolo.setText("La Terra dei Fiordalisi");
        LabelTitolo.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 0)));
        LabelTitolo.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonOpzione, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ButtonNuovaPartita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonContinuaPartita, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(LabelTitolo))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LabelTitolo)
                .addGap(50, 50, 50)
                .addComponent(ButtonNuovaPartita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonContinuaPartita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonOpzione)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNuovaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNuovaPartitaActionPerformed
        // TODO add your handling code here:
        jLabel4.setText(String.valueOf(Creation));
        FrameCreazione.setVisible(true);
    }//GEN-LAST:event_ButtonNuovaPartitaActionPerformed

    private void ButtonMenVelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenVelActionPerformed
        // TODO add your handling code here:
        int vel;
        if(Integer.parseInt(LabelValVel.getText())>0){
            vel=Integer.parseInt(LabelValVel.getText())-1;
            LabelValVel.setText(String.valueOf(vel));
            Creation++;
            jLabel4.setText(String.valueOf(Creation));
        }
        
    }//GEN-LAST:event_ButtonMenVelActionPerformed

    private void ButtonConfremaCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfremaCreaActionPerformed
        // TODO add your handling code here:
        int vel=Integer.parseInt(LabelValVel.getText());
        String nom = TextFieldNome.getText();
        er = new Eroe(nom,vel,vel,vel,vel,vel,vel);
    }//GEN-LAST:event_ButtonConfremaCreaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         int vel;
         if(Creation>0){
             vel=Integer.parseInt(LabelValVel.getText())+1;
            LabelValVel.setText(String.valueOf(vel));
            Creation--;
            jLabel4.setText(String.valueOf(Creation));
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ButtonOpzioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOpzioneActionPerformed
        // TODO add your handling code here:
        FrameOpzione.setVisible(true);
    }//GEN-LAST:event_ButtonOpzioneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game2dForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game2dForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game2dForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game2dForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game2dForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfremaCrea;
    private javax.swing.JButton ButtonContinuaPartita;
    private javax.swing.JButton ButtonMenVel;
    private javax.swing.JButton ButtonNuovaPartita;
    private javax.swing.JButton ButtonOpzione;
    private javax.swing.JButton ButtonSelezionaLIngua;
    private javax.swing.JButton ButtonpiuVel;
    private javax.swing.JComboBox<String> ComboLingue;
    private javax.swing.JFrame FrameCreazione;
    private javax.swing.JFrame FrameOpzione;
    private javax.swing.JLabel LabelLingua;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelTitolo;
    private javax.swing.JLabel LabelTitoloOpzione;
    private javax.swing.JLabel LabelValVel;
    private javax.swing.JLabel LabelVelocita;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
