/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.game2d;

import com.mycompany.game2d.personaggi.Eroe;

import java.awt.*;

/**
 *
 * @author Esposito.Lorenzo
 */
public class LevelUp extends javax.swing.JFrame {
    private Eroe er;
    private int PuntiLivello=20;
    private FrameMappa FM;

    /**
     * Creates new form LevelUp
     */
    public LevelUp() {
        initComponents();
        super.getContentPane().setBackground(Color.BLACK);
        super.setSize(350,320);


    }
    public void setEr(Eroe er) {
        this.er = er;
        LabelValNome.setText(er.getNome());
        jLabel2.setText(String.valueOf(er.getLv()));
        LabelCreazione.setText(String.valueOf(PuntiLivello));
        LabelValVel.setText(String.valueOf(er.getVelocita()));
        LabelValFor.setText(String.valueOf(er.getForza()));
        LabelValArc.setText(String.valueOf(er.getArcana()));
        LabelValDes.setText(String.valueOf(er.getDestrezza()));
        LabelValHP.setText(String.valueOf(er.getHpMax()));
        LabelValMana.setText(String.valueOf(er.getManaMax()));
        LabelValArc.setText(String.valueOf(er.getArcana()));
    }
    public void SetFrameMap(FrameMappa fM){
        FM=fM;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonMenArc = new javax.swing.JButton();
        LabelArcana = new javax.swing.JLabel();
        LabelValDes = new javax.swing.JLabel();
        ButtonMenDes = new javax.swing.JButton();
        LabelDestrzza = new javax.swing.JLabel();
        ButtonpiuDes = new javax.swing.JButton();
        ButtonpiuHP = new javax.swing.JButton();
        LabelValHP = new javax.swing.JLabel();
        ButtonMenHP = new javax.swing.JButton();
        LabelHP = new javax.swing.JLabel();
        LabelVelocita = new javax.swing.JLabel();
        LabelValMana = new javax.swing.JLabel();
        ButtonConfremaCrea = new javax.swing.JButton();
        ButtonpiuMana = new javax.swing.JButton();
        ButtonMenVel = new javax.swing.JButton();
        LabelMana = new javax.swing.JLabel();
        LabelValVel = new javax.swing.JLabel();
        ButtonMenMana = new javax.swing.JButton();
        ButtonpiuVel = new javax.swing.JButton();
        LabelCreazione = new javax.swing.JLabel();
        LabelForza = new javax.swing.JLabel();
        ButtonMenFor = new javax.swing.JButton();
        LabelValFor = new javax.swing.JLabel();
        ButtonpiuFor = new javax.swing.JButton();
        LabelNome = new javax.swing.JLabel();
        LabelValArc = new javax.swing.JLabel();
        ButtonpiuArc = new javax.swing.JButton();
        LabelValNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 296));

        ButtonMenArc.setBackground(new java.awt.Color(84, 84, 84));
        ButtonMenArc.setForeground(new java.awt.Color(232, 232, 232));
        ButtonMenArc.setText("-");
        ButtonMenArc.setToolTipText("n");
        ButtonMenArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenArcActionPerformed(evt);
            }
        });

        LabelArcana.setForeground(new java.awt.Color(232, 232, 232));
        LabelArcana.setText("Arcana");

        LabelValDes.setForeground(new java.awt.Color(232, 232, 232));
        LabelValDes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValDes.setText("5");

        ButtonMenDes.setBackground(new java.awt.Color(84, 84, 84));
        ButtonMenDes.setForeground(new java.awt.Color(232, 232, 232));
        ButtonMenDes.setText("-");
        ButtonMenDes.setToolTipText("a");
        ButtonMenDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenDesActionPerformed(evt);
            }
        });

        LabelDestrzza.setForeground(new java.awt.Color(232, 232, 232));
        LabelDestrzza.setText("Destrzza");

        ButtonpiuDes.setBackground(new java.awt.Color(84, 84, 84));
        ButtonpiuDes.setForeground(new java.awt.Color(232, 232, 232));
        ButtonpiuDes.setText("+");
        ButtonpiuDes.setToolTipText("e");
        ButtonpiuDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpiuDesActionPerformed(evt);
            }
        });

        ButtonpiuHP.setBackground(new java.awt.Color(84, 84, 84));
        ButtonpiuHP.setForeground(new java.awt.Color(232, 232, 232));
        ButtonpiuHP.setText("+");
        ButtonpiuHP.setToolTipText("");
        ButtonpiuHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpiuHPActionPerformed(evt);
            }
        });

        LabelValHP.setForeground(new java.awt.Color(232, 232, 232));
        LabelValHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValHP.setText("10");

        ButtonMenHP.setBackground(new java.awt.Color(84, 84, 84));
        ButtonMenHP.setForeground(new java.awt.Color(232, 232, 232));
        ButtonMenHP.setText("-");
        ButtonMenHP.setToolTipText("m");
        ButtonMenHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenHPActionPerformed(evt);
            }
        });

        LabelHP.setForeground(new java.awt.Color(232, 232, 232));
        LabelHP.setText("HP");

        LabelVelocita.setForeground(new java.awt.Color(232, 232, 232));
        LabelVelocita.setText("Velocita");

        LabelValMana.setForeground(new java.awt.Color(232, 232, 232));
        LabelValMana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValMana.setText("10");

        ButtonConfremaCrea.setBackground(new java.awt.Color(84, 84, 84));
        ButtonConfremaCrea.setForeground(new java.awt.Color(232, 232, 232));
        ButtonConfremaCrea.setText("Conferma");
        ButtonConfremaCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfremaCreaActionPerformed(evt);
            }
        });

        ButtonpiuMana.setBackground(new java.awt.Color(84, 84, 84));
        ButtonpiuMana.setForeground(new java.awt.Color(232, 232, 232));
        ButtonpiuMana.setText("+");
        ButtonpiuMana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpiuManaActionPerformed(evt);
            }
        });

        ButtonMenVel.setBackground(new java.awt.Color(84, 84, 84));
        ButtonMenVel.setForeground(new java.awt.Color(232, 232, 232));
        ButtonMenVel.setText("-");
        ButtonMenVel.setToolTipText("k");
        ButtonMenVel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenVelActionPerformed(evt);
            }
        });

        LabelMana.setForeground(new java.awt.Color(232, 232, 232));
        LabelMana.setText("Mana");

        LabelValVel.setForeground(new java.awt.Color(232, 232, 232));
        LabelValVel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValVel.setText("5");

        ButtonMenMana.setBackground(new java.awt.Color(84, 84, 84));
        ButtonMenMana.setForeground(new java.awt.Color(232, 232, 232));
        ButtonMenMana.setText("-");
        ButtonMenMana.setToolTipText("i");
        ButtonMenMana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenManaActionPerformed(evt);
            }
        });

        ButtonpiuVel.setBackground(new java.awt.Color(84, 84, 84));
        ButtonpiuVel.setForeground(new java.awt.Color(232, 232, 232));
        ButtonpiuVel.setText("+");
        ButtonpiuVel.setToolTipText("c");
        ButtonpiuVel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpiuVelActionPerformed(evt);
            }
        });

        LabelCreazione.setBackground(new java.awt.Color(0, 0, 0));
        LabelCreazione.setForeground(new java.awt.Color(232, 232, 232));

        LabelForza.setForeground(new java.awt.Color(232, 232, 232));
        LabelForza.setText("Forza");

        ButtonMenFor.setBackground(new java.awt.Color(84, 84, 84));
        ButtonMenFor.setForeground(new java.awt.Color(232, 232, 232));
        ButtonMenFor.setText("-");
        ButtonMenFor.setToolTipText("o");
        ButtonMenFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenForActionPerformed(evt);
            }
        });

        LabelValFor.setForeground(new java.awt.Color(232, 232, 232));
        LabelValFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValFor.setText("5");

        ButtonpiuFor.setBackground(new java.awt.Color(84, 84, 84));
        ButtonpiuFor.setForeground(new java.awt.Color(232, 232, 232));
        ButtonpiuFor.setText("+");
        ButtonpiuFor.setToolTipText("o");
        ButtonpiuFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpiuForActionPerformed(evt);
            }
        });

        LabelNome.setForeground(new java.awt.Color(232, 232, 232));
        LabelNome.setText("Nome:");

        LabelValArc.setForeground(new java.awt.Color(232, 232, 232));
        LabelValArc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelValArc.setText("5");

        ButtonpiuArc.setBackground(new java.awt.Color(84, 84, 84));
        ButtonpiuArc.setForeground(new java.awt.Color(232, 232, 232));
        ButtonpiuArc.setText("+");
        ButtonpiuArc.setToolTipText("d");
        ButtonpiuArc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpiuArcActionPerformed(evt);
            }
        });

        LabelValNome.setForeground(new java.awt.Color(232, 232, 232));
        LabelValNome.setText("jLabel1");

        jLabel1.setForeground(new java.awt.Color(232, 232, 232));
        jLabel1.setText("Aumento di livello:");

        jLabel2.setForeground(new java.awt.Color(232, 232, 232));
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelNome)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelVelocita, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelForza, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelDestrzza, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelArcana, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelHP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelMana, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ButtonMenDes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LabelValDes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonpiuDes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ButtonMenMana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonMenHP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonMenArc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelValArc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelValHP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(LabelValMana, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ButtonpiuArc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonpiuHP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonpiuMana, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonMenFor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelValFor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonpiuFor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonMenVel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelValVel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonpiuVel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelValNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelCreazione, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonConfremaCrea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelValNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelCreazione, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonMenVel)
                        .addComponent(LabelVelocita))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonpiuVel)
                        .addComponent(LabelValVel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonMenFor)
                        .addComponent(LabelForza))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonpiuFor)
                        .addComponent(LabelValFor)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonMenArc)
                        .addComponent(LabelArcana))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonpiuArc)
                        .addComponent(LabelValArc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonpiuDes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonMenDes)
                        .addComponent(LabelValDes)
                        .addComponent(LabelDestrzza)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonpiuHP)
                        .addComponent(LabelValHP))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonMenHP)
                        .addComponent(LabelHP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonpiuMana)
                        .addComponent(LabelValMana))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonMenMana)
                        .addComponent(LabelMana)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConfremaCrea)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMenArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenArcActionPerformed
        // TODO add your handling code here:
        diminuisci(LabelValArc, er.getArcana());
    }//GEN-LAST:event_ButtonMenArcActionPerformed

    private void ButtonMenDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenDesActionPerformed
        // TODO add your handling code here:
        diminuisci(LabelValDes, er.getDestrezza());
    }//GEN-LAST:event_ButtonMenDesActionPerformed

    private void ButtonpiuDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpiuDesActionPerformed
        // TODO add your handling code here:
        aumenta(LabelValDes);
    }//GEN-LAST:event_ButtonpiuDesActionPerformed

    private void ButtonpiuHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpiuHPActionPerformed
        // TODO add your handling code here:
        aumenta10(LabelValHP);
    }//GEN-LAST:event_ButtonpiuHPActionPerformed

    private void ButtonMenHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenHPActionPerformed
        // TODO add your handling code here:
        diminuisci10(LabelValHP, er.getHp());
    }//GEN-LAST:event_ButtonMenHPActionPerformed

    private void ButtonConfremaCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfremaCreaActionPerformed
        // TODO add your handling code here:
        if(PuntiLivello==0){
        int forz=Integer.parseInt(LabelValFor.getText());
        int velocita=Integer.parseInt(LabelValVel.getText());
        int arcana=Integer.parseInt(LabelValArc.getText());
        int destrezza=Integer.parseInt(LabelValDes.getText());
        int hp=Integer.parseInt(LabelValHP.getText());
        int mana=Integer.parseInt(LabelValMana.getText());
        er.levelUp(forz, velocita, arcana, destrezza, hp, mana);
        FM.Updatebars();
        super.dispose();
        }
    }//GEN-LAST:event_ButtonConfremaCreaActionPerformed

    private void ButtonpiuManaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpiuManaActionPerformed
        // TODO add your handling code here:
        aumenta10(LabelValMana);
    }//GEN-LAST:event_ButtonpiuManaActionPerformed

    private void ButtonMenVelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenVelActionPerformed
        // TODO add your handling code here:
        diminuisci(LabelValVel, er.getVelocita());

    }//GEN-LAST:event_ButtonMenVelActionPerformed

    private void ButtonMenManaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenManaActionPerformed
        // TODO add your handling code here:
        diminuisci10(LabelValMana, er.getMana());
    }//GEN-LAST:event_ButtonMenManaActionPerformed

    private void ButtonpiuVelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpiuVelActionPerformed
        // TODO add your handling code here:
        aumenta(LabelValVel);
    }//GEN-LAST:event_ButtonpiuVelActionPerformed

    private void ButtonMenForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenForActionPerformed
        // TODO add your handling code here:
        diminuisci(LabelValFor, er.getForza());
    }//GEN-LAST:event_ButtonMenForActionPerformed

    private void ButtonpiuForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpiuForActionPerformed
        // TODO add your handling code here:
        aumenta(LabelValFor);
    }//GEN-LAST:event_ButtonpiuForActionPerformed

    private void ButtonpiuArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpiuArcActionPerformed
        // TODO add your handling code here:
        aumenta(LabelValArc);
    }//GEN-LAST:event_ButtonpiuArcActionPerformed
private void aumenta(javax.swing.JLabel la){
        if(PuntiLivello>0){
            int a = Integer.parseInt(la.getText());
            a++;
            PuntiLivello--;
            la.setText(String.valueOf(a));
            LabelCreazione.setText(String.valueOf(PuntiLivello));
        }
    }
    private void aumenta10(javax.swing.JLabel la){
        int a;
        if(PuntiLivello>0){
            a = Integer.parseInt(la.getText());
            a=a+10;
            PuntiLivello--;
            la.setText(String.valueOf(a));
            LabelCreazione.setText(String.valueOf(PuntiLivello));
        }
    }
    private void diminuisci(javax.swing.JLabel la, int val){
        int a = Integer.parseInt(la.getText());
        if(a>val){
            a--;
            PuntiLivello++;
            la.setText(String.valueOf(a));
            LabelCreazione.setText(String.valueOf(PuntiLivello));
        }
    }
    private void diminuisci10(javax.swing.JLabel la, int val){
        int a = Integer.parseInt(la.getText());
        if(val>a){
            a=a-10;
            PuntiLivello++;
            la.setText(String.valueOf(a));
            LabelCreazione.setText(String.valueOf(PuntiLivello));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfremaCrea;
    private javax.swing.JButton ButtonMenArc;
    private javax.swing.JButton ButtonMenDes;
    private javax.swing.JButton ButtonMenFor;
    private javax.swing.JButton ButtonMenHP;
    private javax.swing.JButton ButtonMenMana;
    private javax.swing.JButton ButtonMenVel;
    private javax.swing.JButton ButtonpiuArc;
    private javax.swing.JButton ButtonpiuDes;
    private javax.swing.JButton ButtonpiuFor;
    private javax.swing.JButton ButtonpiuHP;
    private javax.swing.JButton ButtonpiuMana;
    private javax.swing.JButton ButtonpiuVel;
    private javax.swing.JLabel LabelArcana;
    private javax.swing.JLabel LabelCreazione;
    private javax.swing.JLabel LabelDestrzza;
    private javax.swing.JLabel LabelForza;
    private javax.swing.JLabel LabelHP;
    private javax.swing.JLabel LabelMana;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelValArc;
    private javax.swing.JLabel LabelValDes;
    private javax.swing.JLabel LabelValFor;
    private javax.swing.JLabel LabelValHP;
    private javax.swing.JLabel LabelValMana;
    private javax.swing.JLabel LabelValNome;
    private javax.swing.JLabel LabelValVel;
    private javax.swing.JLabel LabelVelocita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
